#index:
#    path: /
#    controller: App\Controller\DefaultController::index

contact_form_submit:
  path: /api/submit_form/contact
  controller: App\Controller\ContactController::submit

reservation_submit:
  path: /api/submit_form/reservation
  controller: App\Controller\ReservationController::submit
